---
# Tasks file for ansible-clamav

- name: "Include ubuntu tasks"
  include_tasks: "ubuntu.yml"
  when: ( ansible_distribution_release == "xenial" ) or
        ( ansible_distribution_release == "bionic" )

- name: "Include RedHat/CentOS tasks"
  include_tasks: "redhat.yml"
  when:
    - ansible_os_family == "RedHat"

- name: "Pause, give some time for service to get up"
  pause:
    seconds: 10

- name: "check clamdscan is working"
  command: "clamdscan -p 30:1"
