---
# Tasks file for ansible-clamav

- name: "Include ubuntu tasks"
  include_tasks: "ubuntu.yml"
  when:
    - ansible_os_family == "Debian"
    - ansible_distribution_version is version_compare('16.04', '>=')

- name: "Include RedHat/CentOS/Rocky tasks"
  include_tasks: "redhat.yml"
  when:
    - ansible_os_family in ['RedHat','Rocky']

- name: "Pause, give some time for service to get up"
  pause:
    seconds: 10

- name: "check clamdscan is working"
  command: "clamdscan -p 30:1"
