---
- name: "Enable epel repository"
  yum:
    name: "epel-release"
    state: "latest"
  when: install_rpm_repositories|bool

- name: "Install packages required by role (RedHat)"
  yum:
    name: "{{ item }}"
    state: "latest"
  with_items: 
    - "git"
    - "libsemanage-python"

- name: "Install required packages (RedHat)"
  yum:
    name: "{{ item }}"
    state: "latest"
  with_items:
    - "clamav"
    - "clamav-data"
    - "clamav-devel"
    - "clamav-filesystem"
    - "clamav-lib"
    - "clamav-server"
    - "clamav-scanner"
    - "clamav-update"
    - "clamav-scanner-systemd"
    - "clamav-server-systemd"

# If CLAMAV_SOCKET_TYPE is not defined, use tcp option
- set_fact:
    CLAMAV_SOCKET_TYPE: "tcp"
  when:  CLAMAV_SOCKET_TYPE is not defined

- name: "SELinux enable antivirus_can_scan_system"
  seboolean:
    name: antivirus_can_scan_system
    state: yes
    persistent: yes
  when: ansible_selinux.status == "enabled"

- name: "SELinux enable clamd_use_jit"
  seboolean:
    name: clamd_use_jit
    state: yes
    persistent: yes
  when: ansible_selinux.status == "enabled"

- name: "Config /etc/freshclam.conf from template"
  template:
    src: "etc/freshclam.conf.j2"
    dest: "/etc/freshclam.conf"
    backup: "yes"

- name: "Config /etc/sysconfig/freshclam from template"
  template:
    src: "etc/sysconfig/freshclam.j2"
    dest: "/etc/sysconfig/freshclam"
    backup: "yes"

- name: "Include download-sigs.yml"
  include: "download-sigs.yml"

- name: "Config /etc/clamd.d/scan.conf from template"
  template: 
    src: "etc/clamd.d/scan.conf.j2"
    dest: "/etc/clamd.d/scan.conf"
    backup: "yes"

- name: "Symlink /etc/clamd.d/scan.conf to /etc/clamd.conf"
  file:
    src: "/etc/clamd.d/scan.conf"
    dest: "/etc/clamd.conf"
    state: "link"

- name: "Create tmpfiles custom socket directory"
  shell: "echo 'd /var/run/clamav 0755 clamscan clamscan' > /etc/tmpfiles.d/clamd.scam.archivematica.conf"
  when: CLAMAV_SOCKET_TYPE ==  'file'

- name: "Run systemd-tmpfiles to create custom socket directory"
  shell: "systemd-tmpfiles --create /etc/tmpfiles.d/clamd.scam.archivematica.conf"
  when: CLAMAV_SOCKET_TYPE ==  'file'

- name: "Enable and restart services"
  service:
    name: "clamd@scan"
    state: "restarted"
    enabled: "yes"

